version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::307946640046:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-t3t8BHPT6EOb"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::307946640046:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-IMgnrxbbPgV0"
cloudformation_execution_role = "arn:aws:iam::307946640046:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-NfBiSUzAFS12"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-lfhc5xnsmure"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::307946640046:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-7W6QPlSXY674"
cloudformation_execution_role = "arn:aws:iam::307946640046:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-pGHWKcD5DDke"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-itosbumhuvnt"
image_repository = ""
region = "us-east-1"
